package com.midea.isc.api.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.midea.isc.common.model.BasicModel;

@JsonIgnoreProperties(value = {
		"attribute1", "attribute2", "attribute3", "attribute4", "attribute5"} , ignoreUnknown = true)
public class Application extends BasicModel {	
		private java.lang.String application;   	private java.lang.String type;   	private java.lang.String name;   	private java.lang.String icon;   	private java.lang.String url;   	private java.lang.Integer topMenuId;   	private java.lang.String relationship;   	private java.lang.String enableFlag;   	private java.lang.String visibleFlag;   	private java.lang.Integer defaultSequence;   	private java.lang.String auth;   	private java.lang.String webRoot;   	private java.lang.String adminEmail;   	private java.lang.String adminPwd;   	public java.lang.String getApplication() {	    return this.application;	}	public void setApplication(java.lang.String application) {	    this.application=application;	}	public java.lang.String getType() {	    return this.type;	}	public void setType(java.lang.String type) {	    this.type=type;	}	public java.lang.String getName() {	    return this.name;	}	public void setName(java.lang.String name) {	    this.name=name;	}	public java.lang.String getIcon() {	    return this.icon;	}	public void setIcon(java.lang.String icon) {	    this.icon=icon;	}	public java.lang.String getUrl() {	    return this.url;	}	public void setUrl(java.lang.String url) {	    this.url=url;	}	public java.lang.Integer getTopMenuId() {	    return this.topMenuId;	}	public void setTopMenuId(java.lang.Integer topMenuId) {	    this.topMenuId=topMenuId;	}	public java.lang.String getRelationship() {	    return this.relationship;	}	public void setRelationship(java.lang.String relationship) {	    this.relationship=relationship;	}	public java.lang.String getEnableFlag() {	    return this.enableFlag;	}	public void setEnableFlag(java.lang.String enableFlag) {	    this.enableFlag=enableFlag;	}	public java.lang.String getVisibleFlag() {	    return this.visibleFlag;	}	public void setVisibleFlag(java.lang.String visibleFlag) {	    this.visibleFlag=visibleFlag;	}	public java.lang.Integer getDefaultSequence() {	    return this.defaultSequence;	}	public void setDefaultSequence(java.lang.Integer defaultSequence) {	    this.defaultSequence=defaultSequence;	}	public java.lang.String getAuth() {	    return this.auth;	}	public void setAuth(java.lang.String auth) {	    this.auth=auth;	}	public java.lang.String getWebRoot() {	    return this.webRoot;	}	public void setWebRoot(java.lang.String webRoot) {	    this.webRoot=webRoot;	}	public java.lang.String getAdminEmail() {	    return this.adminEmail;	}	public void setAdminEmail(java.lang.String adminEmail) {	    this.adminEmail=adminEmail;	}	public java.lang.String getAdminPwd() {	    return this.adminPwd;	}	public void setAdminPwd(java.lang.String adminPwd) {	    this.adminPwd=adminPwd;	}
}

