package com.midea.isc.api.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.midea.isc.common.model.BasicModel;

@JsonIgnoreProperties(value = {
		"attribute1", "attribute2", "attribute3", "attribute4", "attribute5"} , ignoreUnknown = true)
public class CurrencyFormat extends BasicModel {	
		private java.lang.Integer formatId;   	private java.lang.String currencyCode;   	private java.lang.String currencySymbol;   	private java.lang.String territoryCode;   	private java.lang.String description;   	private java.lang.Integer currencyPrecision;   	private java.lang.String thousandsSeparator;   	private java.lang.String decimalSeparator;   	private java.lang.Integer calculatedPrecision;   	private java.lang.String enabled;   	public java.lang.Integer getFormatId() {	    return this.formatId;	}	public void setFormatId(java.lang.Integer formatId) {	    this.formatId=formatId;	}	public java.lang.String getCurrencyCode() {	    return this.currencyCode;	}	public void setCurrencyCode(java.lang.String currencyCode) {	    this.currencyCode=currencyCode;	}	public java.lang.String getCurrencySymbol() {	    return this.currencySymbol;	}	public void setCurrencySymbol(java.lang.String currencySymbol) {	    this.currencySymbol=currencySymbol;	}	public java.lang.String getTerritoryCode() {	    return this.territoryCode;	}	public void setTerritoryCode(java.lang.String territoryCode) {	    this.territoryCode=territoryCode;	}	public java.lang.String getDescription() {	    return this.description;	}	public void setDescription(java.lang.String description) {	    this.description=description;	}	public java.lang.Integer getCurrencyPrecision() {	    return this.currencyPrecision;	}	public void setCurrencyPrecision(java.lang.Integer currencyPrecision) {	    this.currencyPrecision=currencyPrecision;	}	public java.lang.String getThousandsSeparator() {	    return this.thousandsSeparator;	}	public void setThousandsSeparator(java.lang.String thousandsSeparator) {	    this.thousandsSeparator=thousandsSeparator;	}	public java.lang.String getDecimalSeparator() {	    return this.decimalSeparator;	}	public void setDecimalSeparator(java.lang.String decimalSeparator) {	    this.decimalSeparator=decimalSeparator;	}	public java.lang.Integer getCalculatedPrecision() {	    return this.calculatedPrecision;	}	public void setCalculatedPrecision(java.lang.Integer calculatedPrecision) {	    this.calculatedPrecision=calculatedPrecision;	}	public java.lang.String getEnabled() {	    return this.enabled;	}	public void setEnabled(java.lang.String enabled) {	    this.enabled=enabled;	}
}

