package com.midea.isc.api.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.midea.isc.common.model.BasicModel;

@JsonIgnoreProperties(value = {
		"attribute1", "attribute2", "attribute3", "attribute4", "attribute5"} , ignoreUnknown = true)
public class View extends BasicModel {	
		private java.lang.Integer viewId;   	private java.lang.String viewName;   	private java.lang.String loginId;   //使用者mip账号	private java.lang.Integer pageSize;   //分页大小	private java.lang.String showFilter;   //是否显示过滤条  Y/N	private java.lang.String pageId;   //页面	private java.lang.String gridId;   //表格	private java.lang.String sortField;   //排序字段	private java.lang.String sortDirection;   //升序/降序 ASC/DESC	private java.lang.String application;   	private java.lang.String appShare;   //是否应用内共享	private java.lang.String defaultFlag;   //是否默认	public java.lang.Integer getViewId() {	    return this.viewId;	}	public void setViewId(java.lang.Integer viewId) {	    this.viewId=viewId;	}	public java.lang.String getViewName() {	    return this.viewName;	}	public void setViewName(java.lang.String viewName) {	    this.viewName=viewName;	}	public java.lang.String getLoginId() {	    return this.loginId;	}	public void setLoginId(java.lang.String loginId) {	    this.loginId=loginId;	}	public java.lang.Integer getPageSize() {	    return this.pageSize;	}	public void setPageSize(java.lang.Integer pageSize) {	    this.pageSize=pageSize;	}	public java.lang.String getShowFilter() {	    return this.showFilter;	}	public void setShowFilter(java.lang.String showFilter) {	    this.showFilter=showFilter;	}	public java.lang.String getPageId() {	    return this.pageId;	}	public void setPageId(java.lang.String pageId) {	    this.pageId=pageId;	}	public java.lang.String getGridId() {	    return this.gridId;	}	public void setGridId(java.lang.String gridId) {	    this.gridId=gridId;	}	public java.lang.String getSortField() {	    return this.sortField;	}	public void setSortField(java.lang.String sortField) {	    this.sortField=sortField;	}	public java.lang.String getSortDirection() {	    return this.sortDirection;	}	public void setSortDirection(java.lang.String sortDirection) {	    this.sortDirection=sortDirection;	}	public java.lang.String getApplication() {	    return this.application;	}	public void setApplication(java.lang.String application) {	    this.application=application;	}	public java.lang.String getAppShare() {	    return this.appShare;	}	public void setAppShare(java.lang.String appShare) {	    this.appShare=appShare;	}	public java.lang.String getDefaultFlag() {	    return this.defaultFlag;	}	public void setDefaultFlag(java.lang.String defaultFlag) {	    this.defaultFlag=defaultFlag;	}
}

