package com.midea.isc.attachment.param;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import com.midea.isc.attachment.model.AttachmentList;

@JsonIgnoreProperties(ignoreUnknown = true)
public class AttachmentListParam extends AttachmentList {
	// 字段比较符
	private java.lang.String attachmentIdCond;   	private java.lang.String referenceTableCond;   	private java.lang.String referenceIdCond;   	private java.lang.String applicationCond;   	private java.lang.String displayNameCond;   	private java.lang.String fileNameCond;   	private java.lang.String fileDirectoryCond;   	private java.lang.String fileSizeCond;   	private java.lang.String fileTypeCond;   	public java.lang.String getAttachmentIdCond() {	    return this.attachmentIdCond;	}	public void setAttachmentIdCond(java.lang.String attachmentIdCond) {	    this.attachmentIdCond=attachmentIdCond;	}	public java.lang.String getReferenceTableCond() {	    return this.referenceTableCond;	}	public void setReferenceTableCond(java.lang.String referenceTableCond) {	    this.referenceTableCond=referenceTableCond;	}	public java.lang.String getReferenceIdCond() {	    return this.referenceIdCond;	}	public void setReferenceIdCond(java.lang.String referenceIdCond) {	    this.referenceIdCond=referenceIdCond;	}	public java.lang.String getApplicationCond() {	    return this.applicationCond;	}	public void setApplicationCond(java.lang.String applicationCond) {	    this.applicationCond=applicationCond;	}	public java.lang.String getDisplayNameCond() {	    return this.displayNameCond;	}	public void setDisplayNameCond(java.lang.String displayNameCond) {	    this.displayNameCond=displayNameCond;	}	public java.lang.String getFileNameCond() {	    return this.fileNameCond;	}	public void setFileNameCond(java.lang.String fileNameCond) {	    this.fileNameCond=fileNameCond;	}	public java.lang.String getFileDirectoryCond() {	    return this.fileDirectoryCond;	}	public void setFileDirectoryCond(java.lang.String fileDirectoryCond) {	    this.fileDirectoryCond=fileDirectoryCond;	}	public java.lang.String getFileSizeCond() {	    return this.fileSizeCond;	}	public void setFileSizeCond(java.lang.String fileSizeCond) {	    this.fileSizeCond=fileSizeCond;	}	public java.lang.String getFileTypeCond() {	    return this.fileTypeCond;	}	public void setFileTypeCond(java.lang.String fileTypeCond) {	    this.fileTypeCond=fileTypeCond;	}	
}
