package com.midea.isc.api.param;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import com.midea.isc.api.model.Currency;

@JsonIgnoreProperties(ignoreUnknown = true)
public class CurrencyParam extends Currency {
	// 字段比较符
	private java.lang.String currencyIdCond;   	private java.lang.String codeCond;   	private java.lang.String symbolCond;   	private java.lang.String descriptionCond;   	private java.lang.String currencyPrecisionCond;   	private java.lang.String thousandsSeparatorCond;   	private java.lang.String decimalSeparatorCond;   	private java.lang.String calculatedPrecisionCond;   	private java.lang.String enabledCond;   	public java.lang.String getCurrencyIdCond() {	    return this.currencyIdCond;	}	public void setCurrencyIdCond(java.lang.String currencyIdCond) {	    this.currencyIdCond=currencyIdCond;	}	public java.lang.String getCodeCond() {	    return this.codeCond;	}	public void setCodeCond(java.lang.String codeCond) {	    this.codeCond=codeCond;	}	public java.lang.String getSymbolCond() {	    return this.symbolCond;	}	public void setSymbolCond(java.lang.String symbolCond) {	    this.symbolCond=symbolCond;	}	public java.lang.String getDescriptionCond() {	    return this.descriptionCond;	}	public void setDescriptionCond(java.lang.String descriptionCond) {	    this.descriptionCond=descriptionCond;	}	public java.lang.String getCurrencyPrecisionCond() {	    return this.currencyPrecisionCond;	}	public void setCurrencyPrecisionCond(java.lang.String currencyPrecisionCond) {	    this.currencyPrecisionCond=currencyPrecisionCond;	}	public java.lang.String getThousandsSeparatorCond() {	    return this.thousandsSeparatorCond;	}	public void setThousandsSeparatorCond(java.lang.String thousandsSeparatorCond) {	    this.thousandsSeparatorCond=thousandsSeparatorCond;	}	public java.lang.String getDecimalSeparatorCond() {	    return this.decimalSeparatorCond;	}	public void setDecimalSeparatorCond(java.lang.String decimalSeparatorCond) {	    this.decimalSeparatorCond=decimalSeparatorCond;	}	public java.lang.String getCalculatedPrecisionCond() {	    return this.calculatedPrecisionCond;	}	public void setCalculatedPrecisionCond(java.lang.String calculatedPrecisionCond) {	    this.calculatedPrecisionCond=calculatedPrecisionCond;	}	public java.lang.String getEnabledCond() {	    return this.enabledCond;	}	public void setEnabledCond(java.lang.String enabledCond) {	    this.enabledCond=enabledCond;	}	
}
