package com.midea.isc.api.param;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import com.midea.isc.api.model.CurrencyFormat;

@JsonIgnoreProperties(ignoreUnknown = true)
public class CurrencyFormatParam extends CurrencyFormat {
	// 字段比较符
	private java.lang.String formatIdCond;   	private java.lang.String currencyCodeCond;   	private java.lang.String currencySymbolCond;   	private java.lang.String territoryCodeCond;   	private java.lang.String descriptionCond;   	private java.lang.String currencyPrecisionCond;   	private java.lang.String thousandsSeparatorCond;   	private java.lang.String decimalSeparatorCond;   	private java.lang.String calculatedPrecisionCond;   	private java.lang.String enabledCond;   	public java.lang.String getFormatIdCond() {	    return this.formatIdCond;	}	public void setFormatIdCond(java.lang.String formatIdCond) {	    this.formatIdCond=formatIdCond;	}	public java.lang.String getCurrencyCodeCond() {	    return this.currencyCodeCond;	}	public void setCurrencyCodeCond(java.lang.String currencyCodeCond) {	    this.currencyCodeCond=currencyCodeCond;	}	public java.lang.String getCurrencySymbolCond() {	    return this.currencySymbolCond;	}	public void setCurrencySymbolCond(java.lang.String currencySymbolCond) {	    this.currencySymbolCond=currencySymbolCond;	}	public java.lang.String getTerritoryCodeCond() {	    return this.territoryCodeCond;	}	public void setTerritoryCodeCond(java.lang.String territoryCodeCond) {	    this.territoryCodeCond=territoryCodeCond;	}	public java.lang.String getDescriptionCond() {	    return this.descriptionCond;	}	public void setDescriptionCond(java.lang.String descriptionCond) {	    this.descriptionCond=descriptionCond;	}	public java.lang.String getCurrencyPrecisionCond() {	    return this.currencyPrecisionCond;	}	public void setCurrencyPrecisionCond(java.lang.String currencyPrecisionCond) {	    this.currencyPrecisionCond=currencyPrecisionCond;	}	public java.lang.String getThousandsSeparatorCond() {	    return this.thousandsSeparatorCond;	}	public void setThousandsSeparatorCond(java.lang.String thousandsSeparatorCond) {	    this.thousandsSeparatorCond=thousandsSeparatorCond;	}	public java.lang.String getDecimalSeparatorCond() {	    return this.decimalSeparatorCond;	}	public void setDecimalSeparatorCond(java.lang.String decimalSeparatorCond) {	    this.decimalSeparatorCond=decimalSeparatorCond;	}	public java.lang.String getCalculatedPrecisionCond() {	    return this.calculatedPrecisionCond;	}	public void setCalculatedPrecisionCond(java.lang.String calculatedPrecisionCond) {	    this.calculatedPrecisionCond=calculatedPrecisionCond;	}	public java.lang.String getEnabledCond() {	    return this.enabledCond;	}	public void setEnabledCond(java.lang.String enabledCond) {	    this.enabledCond=enabledCond;	}	
}
