package com.midea.isc.api.param;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import com.midea.isc.api.model.LovValue;

@JsonIgnoreProperties(ignoreUnknown = true)
public class LovValueParam extends LovValue {
	// 字段比较符
	private java.lang.String valueIdCond;   	private java.lang.String typeIdCond;   	private java.lang.String typeCodeCond;   	private java.lang.String valueCond;   	private java.lang.String descriptionCond;   	private java.lang.String parentIdCond;   	private java.lang.String parentValueCond;   	private java.lang.String seqCond;   	private java.lang.String enableCond;   	private java.lang.String labelCond;   	public java.lang.String getValueIdCond() {	    return this.valueIdCond;	}	public void setValueIdCond(java.lang.String valueIdCond) {	    this.valueIdCond=valueIdCond;	}	public java.lang.String getTypeIdCond() {	    return this.typeIdCond;	}	public void setTypeIdCond(java.lang.String typeIdCond) {	    this.typeIdCond=typeIdCond;	}	public java.lang.String getTypeCodeCond() {	    return this.typeCodeCond;	}	public void setTypeCodeCond(java.lang.String typeCodeCond) {	    this.typeCodeCond=typeCodeCond;	}	public java.lang.String getValueCond() {	    return this.valueCond;	}	public void setValueCond(java.lang.String valueCond) {	    this.valueCond=valueCond;	}	public java.lang.String getDescriptionCond() {	    return this.descriptionCond;	}	public void setDescriptionCond(java.lang.String descriptionCond) {	    this.descriptionCond=descriptionCond;	}	public java.lang.String getParentIdCond() {	    return this.parentIdCond;	}	public void setParentIdCond(java.lang.String parentIdCond) {	    this.parentIdCond=parentIdCond;	}	public java.lang.String getParentValueCond() {	    return this.parentValueCond;	}	public void setParentValueCond(java.lang.String parentValueCond) {	    this.parentValueCond=parentValueCond;	}	public java.lang.String getSeqCond() {	    return this.seqCond;	}	public void setSeqCond(java.lang.String seqCond) {	    this.seqCond=seqCond;	}	public java.lang.String getEnableCond() {	    return this.enableCond;	}	public void setEnableCond(java.lang.String enableCond) {	    this.enableCond=enableCond;	}	public java.lang.String getLabelCond() {	    return this.labelCond;	}	public void setLabelCond(java.lang.String labelCond) {	    this.labelCond=labelCond;	}	
}
