package com.midea.isc.api.param;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import com.midea.isc.api.model.View;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ViewParam extends View {
	// 字段比较符
	private java.lang.String viewIdCond;   	private java.lang.String viewNameCond;   	private java.lang.String loginIdCond;   	private java.lang.String pageSizeCond;   	private java.lang.String showFilterCond;   	private java.lang.String pageIdCond;   	private java.lang.String gridIdCond;   	private java.lang.String sortFieldCond;   	private java.lang.String sortDirectionCond;   	private java.lang.String applicationCond;   	private java.lang.String appShareCond;   	private java.lang.String defaultFlagCond;   	public java.lang.String getViewIdCond() {	    return this.viewIdCond;	}	public void setViewIdCond(java.lang.String viewIdCond) {	    this.viewIdCond=viewIdCond;	}	public java.lang.String getViewNameCond() {	    return this.viewNameCond;	}	public void setViewNameCond(java.lang.String viewNameCond) {	    this.viewNameCond=viewNameCond;	}	public java.lang.String getLoginIdCond() {	    return this.loginIdCond;	}	public void setLoginIdCond(java.lang.String loginIdCond) {	    this.loginIdCond=loginIdCond;	}	public java.lang.String getPageSizeCond() {	    return this.pageSizeCond;	}	public void setPageSizeCond(java.lang.String pageSizeCond) {	    this.pageSizeCond=pageSizeCond;	}	public java.lang.String getShowFilterCond() {	    return this.showFilterCond;	}	public void setShowFilterCond(java.lang.String showFilterCond) {	    this.showFilterCond=showFilterCond;	}	public java.lang.String getPageIdCond() {	    return this.pageIdCond;	}	public void setPageIdCond(java.lang.String pageIdCond) {	    this.pageIdCond=pageIdCond;	}	public java.lang.String getGridIdCond() {	    return this.gridIdCond;	}	public void setGridIdCond(java.lang.String gridIdCond) {	    this.gridIdCond=gridIdCond;	}	public java.lang.String getSortFieldCond() {	    return this.sortFieldCond;	}	public void setSortFieldCond(java.lang.String sortFieldCond) {	    this.sortFieldCond=sortFieldCond;	}	public java.lang.String getSortDirectionCond() {	    return this.sortDirectionCond;	}	public void setSortDirectionCond(java.lang.String sortDirectionCond) {	    this.sortDirectionCond=sortDirectionCond;	}	public java.lang.String getApplicationCond() {	    return this.applicationCond;	}	public void setApplicationCond(java.lang.String applicationCond) {	    this.applicationCond=applicationCond;	}	public java.lang.String getAppShareCond() {	    return this.appShareCond;	}	public void setAppShareCond(java.lang.String appShareCond) {	    this.appShareCond=appShareCond;	}	public java.lang.String getDefaultFlagCond() {	    return this.defaultFlagCond;	}	public void setDefaultFlagCond(java.lang.String defaultFlagCond) {	    this.defaultFlagCond=defaultFlagCond;	}	
}
